<?php

namespace ZIMZIM\ConstructionSiteBundle\Model;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;

/**
 * TypeActionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeActionItemRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source, TokenStorage $token, AuthorizationChecker $checker )
    {
        return $source;
    }
}
