services:
    zimzim_constructionsite.event.constructionsite:
        class: ZIMZIM\ConstructionSiteBundle\Event\ConstructionSiteEvent
    zimzim_constructionsite.event.typeactionitem:
        class: ZIMZIM\ConstructionSiteBundle\Event\TypeActionItemEvent
    zimzim_constructionsite.event.actionitem:
        class: ZIMZIM\ConstructionSiteBundle\Event\ActionItemEvent