zimzim_constructionsite_constructionsite:
    path:     /
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:index" }

zimzim_constructionsite_constructionsite_show:
    path:     /{id}/show/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:show" }

zimzim_constructionsite_constructionsite_new:
    path:     /new/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:new" }

zimzim_constructionsite_constructionsite_create:
    path:     /create/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:create" }
    methods:  POST

zimzim_constructionsite_constructionsite_edit:
    path:     /{id}/edit/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:edit" }

zimzim_constructionsite_constructionsite_update:
    path:     /{id}/update/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:update" }
    methods:  [POST, PUT]

zimzim_constructionsite_constructionsite_delete:
    path:     /{id}/delete/
    defaults: { _controller: "ZIMZIMConstructionSiteBundle:ConstructionSite:delete" }
    methods:  [POST, DELETE]
